In [77]:

import pandas as pd
import numpy as np

df = pd.read_csv("IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [79]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [81]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [83]:
df.shape

(150, 5)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [87]:
df.describe()

#Mostly numeric (unless include='all')

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [89]:
df.isnull().sum()
#Count missing values per column

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [91]:
#Install	pip install scikit-learn
#Import	   from sklearn import preprocessing

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()   # creating a object of the MinMaxScaler class to implement method - fit, transform

In [93]:
x = df.iloc[:, :4]   #integer-location based indexing
#           |    |
#          rows  cols      so selecting first 4 cols

# Alternative method 

x = df.loc[[101, 104], ['Name', 'City', 'Age']]   label based i.e  uses names of cols

x = df[df.columns[:4]]  slicing method

In [95]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [97]:
x_scaled = min_max_scaler.fit_transform(x)

#min_max_scaler: This is an obj of MinMaxScaler from sklearn.preprocessing. It’s used to scale/normalize the data to a range — typically [0, 1].

#fit(x): Calculates the minimum and maximum values for each column in x.
#transform(x): Scales the data based on those minimum and maximum values.

#    X scaled = X​ −X min 
#             -------------             
#              X max −X min


#Appling it separately
#scaler.fit(df)
#df_scaled = scaler.transform(df)   always save in var for transform

In [99]:
df_normalized = pd.DataFrame(x_scaled)
# Takes the scaled data from x_scaled (which is a numpy array) and converts it into a DataFrame

df_normalized

            0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [101]:
df['species'].unique()

# returns an array of unique values (no duplicates)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

Using label Encoder Now Converting categorical variable into numerical -- required order, so applying for only species column

In [104]:
label_encoder = preprocessing.LabelEncoder() 
#encode categorical labels into numerical values and works if there is an actual order like high, medium, low otherwise one-hot encoder

df['species'] = label_encoder.fit_transform(df['species'])

#fit(): This method learns the unique categories (labels) in the column and assigns them an integer.
#transform(): This method replaces the categorical values with corresponding integers.

In [106]:
df['species'].unique()

array([0, 1, 2])

In [108]:
features_df = df.drop(columns=['species']) 
# new DataFrame (features_df) withoout species col
#you may want to separate features (the independent variables) from the target variable (the dependent variable).




Using One hot Encoder Now Converting categorical variable into numerical -- required order, so applying for only species column

In [111]:
enc = preprocessing.OneHotEncoder()  
#useful when you have categorical features with no order and encode categorical labels into binary not numbers 
#Result: This will give you a sparse matrix of encoded values

enc_df=pd.DataFrame(enc.fit_transform(df[['species']]).toarray())
#toarray(): Converts the sparse matrix returned by fit_transform() into a regular NumPy array

#Before feeding them into a machine learning model

In [114]:
df_encode = features_df.join(enc_df)
# joins the features_df DataFrame with enc_df along the index  combining different types of features into a single DataFrame


df_encode.head()

   sepal_length  sepal_width  petal_length  petal_width    0    1    2
0           5.1          3.5           1.4          0.2  1.0  0.0  0.0
1           4.9          3.0           1.4          0.2  1.0  0.0  0.0
2           4.7          3.2           1.3          0.2  1.0  0.0  0.0
3           4.6          3.1           1.5          0.2  1.0  0.0  0.0
4           5.0          3.6           1.4          0.2  1.0  0.0  0.0

In [116]:
df_encode.rename(columns = {0:'Iris-Setosa',
                            1:'Iris-Versicolor',
                            2:'Iris-virginica'}, inplace = True)


# Inplace- It tells pandas to make the changes directly to the DataFrame (i.e., modify it "in place") without returning a new copy

In [118]:
df_encode.head()

,sepal_length,sepal_width,petal_length,petal_width,Iris-Setosa,Iris-Versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0

In [120]:
df['species'].unique()

array([0, 1, 2])

In [122]:
one_hot_df = pd.get_dummies(
    df,                      # original DataFrame
    prefix="Species",        # prefix for new column names
    columns=['species'],     # column(s) to encode
    drop_first=True          # drop the first category to avoid 'multicollinearity'- contain similar information about the variance in the target
                             # (dependent) variable. It makes it hard to determine the effect of each independent variable.
)

#convert categorical variables into dummy/indicator variables (also called one-hot encoding).
# Pandas function returs whole dataframe not sparse matrix like OneHotEncoder

In [124]:
one_hot_df.head()

   sepal_length  sepal_width  petal_length  petal_width  Species_1  Species_2
0           5.1          3.5           1.4          0.2      False      False
1           4.9          3.0           1.4          0.2      False      False
2           4.7          3.2           1.3          0.2      False      False
3           4.6          3.1           1.5          0.2      False      False
4           5.0          3.6           1.4          0.2      False      False

In [126]:
#  Output- Species_Iris-versicolor  Species_Iris-virginica BUT
#  species_1 and species_2 indicates that pandas automatically assigned numeric names 
#  because your species column probably contained numeric values or categorical labels already encoded as numbers.

In [128]:
print(one_hot_df.dtypes)

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
Species_1          bool
Species_2          bool
dtype: object

In [130]:
one_df = np.ceil(one_hot_df).astype(int)

In [140]:
print(one_df.dtypes)

sepal_length    int32
sepal_width     int32
petal_length    int32
petal_width     int32
Species_1       int32
Species_2       int32
dtype: object

In [142]:
one_df.head()

   sepal_length  sepal_width  petal_length  petal_width  Species_1  Species_2
0             6            4             2            1          0          0
1             5            3             2            1          0          0
2             5            4             2            1          0          0
3             5            4             2            1          0          0
4             5            4             2            1          0          0