In [63]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [65]:
df=pd.read_csv("IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [67]:
df .tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [69]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [73]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [75]:
dff=df.iloc[:,:4]

In [77]:
min_max=preprocessing.MinMaxScaler()
df_scaled=min_max.fit_transform(dff)

In [79]:
df_normalised=pd.DataFrame(df_scaled)

In [81]:
df_normalised.head()

          0         1         2         3
0  0.222222  0.625000  0.067797  0.041667
1  0.166667  0.416667  0.067797  0.041667
2  0.111111  0.500000  0.050847  0.041667
3  0.083333  0.458333  0.084746  0.041667
4  0.194444  0.666667  0.067797  0.041667

In [83]:
df_normalised=np.ceil(df_normalised).astype(int)

In [85]:
df_normalised.head()

   0  1  2  3
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1
3  1  1  1  1
4  1  1  1  1

In [87]:
label_encoder=preprocessing.LabelEncoder()
df["species"]=label_encoder.fit_transform(df["species"])
#df["species"]=pd.DataFrame(df["species"])
df["species"].head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int32

In [106]:
first_df=df.drop(columns=["species"])
one_hot_enc=preprocessing.OneHotEncoder()
df_enc=pd.DataFrame(one_hot_enc.fit_transform(df[["species"]]).toarray())

In [122]:
df_fin=first_df.join(df_enc)
df_fin.head()

   sepal_length  sepal_width  petal_length  petal_width    0    1    2
0           5.1          3.5           1.4          0.2  1.0  0.0  0.0
1           4.9          3.0           1.4          0.2  1.0  0.0  0.0
2           4.7          3.2           1.3          0.2  1.0  0.0  0.0
3           4.6          3.1           1.5          0.2  1.0  0.0  0.0
4           5.0          3.6           1.4          0.2  1.0  0.0  0.0

In [ ]:
df_fin.rename(columns={
                        0:"Iris-Setosa",
                        1:"Iris-Ve"
})

In [112]:
df_df=pd.get_dummies(df,prefix="Species",columns=["species"],drop_first=True)

In [114]:
df_df.head()

   sepal_length  sepal_width  petal_length  petal_width  Species_1  Species_2
0           5.1          3.5           1.4          0.2      False      False
1           4.9          3.0           1.4          0.2      False      False
2           4.7          3.2           1.3          0.2      False      False
3           4.6          3.1           1.5          0.2      False      False
4           5.0          3.6           1.4          0.2      False      False

In [116]:
df_df=np.ceil(df_df).astype(int)

In [118]:
df_df.head()

   sepal_length  sepal_width  petal_length  petal_width  Species_1  Species_2
0             6            4             2            1          0          0
1             5            3             2            1          0          0
2             5            4             2            1          0          0
3             5            4             2            1          0          0
4             5            4             2            1          0          0