In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("Mall_Customers.csv")

In [7]:
print(df)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [9]:
df=df.rename(columns={'Annual Income (k$)': 'Income'})

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Income                  200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [13]:
#df.iloc[:,2].mean()   OR    df.loc[:,'Age'].mean()
print("Mean Age:", df['Age'].mean())
print("Median Age:", df['Age'].median())
print("Mode Age:", df['Age'].mode())

Mean Age: 38.85
Median Age: 36.0
Mode Age: 0    32
Name: Age, dtype: int64

0    28
1    3

meaning both 28 and 32 are equally most frequent!2

In [16]:
#df.loc[:,'CustomerID'].mean()

print("Mean CustomerID:", df['CustomerID'].mean())
print("Median CustomerID:", df['CustomerID'].median())
print("Mode of CustomerID:\n", df['CustomerID'].mode())

Mean CustomerID: 100.5
Median CustomerID: 100.5
Mode of CustomerID:
 0        1
1        2
2        3
3        4
4        5
      ...
195    196
196    197
197    198
198    199
199    200
Name: CustomerID, Length: 200, dtype: int64

In [18]:
# Only select numeric columns
numeric_df = df.select_dtypes(include=[np.number])

# Row-wise mean and median (for first 4 rows)
print("\nRow-wise Mean (first 4 rows):\n", numeric_df.mean(axis=1).head(4))
print("\nRow-wise Median (first 4 rows):\n", numeric_df.median(axis=1).head(4))
print("\nRow-wise Mode (first 4 rows):\n", numeric_df.mode(axis=1).head(4))

Row-wise Mean (first 4 rows):
 0    18.50
1    29.75
2    11.25
3    30.00
dtype: float64

Row-wise Median (first 4 rows):
 0    17.0
1    18.0
2    11.0
3    19.5
dtype: float64

Row-wise Mode (first 4 rows):
      0     1     2     3
0  1.0  15.0  19.0  39.0
1  2.0  15.0  21.0  81.0
2  3.0   6.0  16.0  20.0
3  4.0  16.0  23.0  77.0

But CustomerID is unique for each row —
it's just 1, 2, 3, 4, ..., 200 without repetition!

🔵 That means:

Every CustomerID appears exactly once.

In [21]:
print("Overall Mean & Median:\n")
print("Mean values:\n", numeric_df.mean())
print("\nMedian values:\n", numeric_df.median())
print("\nMode values:\n", df.mode())

Overall Mean & Median:

Mean values:
 CustomerID                100.50
Age                        38.85
Income                     60.56
Spending Score (1-100)     50.20
dtype: float64

Median values:
 CustomerID                100.5
Age                        36.0
Income                     61.5
Spending Score (1-100)     50.0
dtype: float64

Mode values:
      CustomerID   Genre   Age  Income  Spending Score (1-100)
0             1  Female  32.0    54.0                    42.0
1             2     NaN   NaN    78.0                     NaN
2             3     NaN   NaN     NaN                     NaN
3             4     NaN   NaN     NaN                     NaN
4             5     NaN   NaN     NaN                     NaN
..          ...     ...   ...     ...                     ...
195         196     NaN   NaN     NaN                     NaN
196         197     NaN   NaN     NaN                     NaN
197         198     NaN   NaN     NaN                     NaN
198         199     NaN   NaN     NaN                     NaN
199         200     NaN   NaN     NaN                     NaN

[200 rows x 5 columns]


Many columns have only one true mode, and the rest are NaN.

In [24]:
df.groupby(['Genre']) ['Age'].mean()

Genre
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [26]:
# Max values
print("Maximum Values:\n", df.max())

Maximum Values:
 CustomerID                 200
Genre                     Male
Age                         70
Income                     137
Spending Score (1-100)      99
dtype: object



Mode	                                                                            Max
Most frequent value (who appears most often)	Alphabetically last value (not about frequency)

"Male" comes after "Female" (because 'M' > 'F') in the alphabet.

In [29]:
# Min values
print("Minimum Values:\n", df.min())

Minimum Values:
 CustomerID                     1
Genre                     Female
Age                           18
Income                        15
Spending Score (1-100)         1
dtype: object

In [34]:
print(df[['CustomerID', 'Age', 'Income', 'Spending Score (1-100)']].std())  #([[...]]) are used to select multiple columns from a DataFrame.

CustomerID                57.879185
Age                       13.969007
Income                    26.264721
Spending Score (1-100)    25.823522
dtype: float64

# Mapping manually  - suitable only for 2 categories or less

df['Genre'] = df['Genre'].map({'Female': 0, 'Male': 1})

#Rowise
df.std(axis=1)[0:4]

# List categorical to numerical

In [40]:
from sklearn import preprocessing

In [41]:
enc = preprocessing.OneHotEncoder()

In [42]:
enc_df = pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())

In [43]:
enc_df

       0    1
0    0.0  1.0
1    0.0  1.0
2    1.0  0.0
3    1.0  0.0
4    1.0  0.0
..   ...  ...
195  1.0  0.0
196  1.0  0.0
197  0.0  1.0
198  0.0  1.0
199  0.0  1.0

[200 rows x 2 columns]

In [48]:
df_encode =df.join(enc_df)

In [50]:
df_encode

     CustomerID   Genre  Age  Income  Spending Score (1-100)    0    1
0             1    Male   19      15                      39  0.0  1.0
1             2    Male   21      15                      81  0.0  1.0
2             3  Female   20      16                       6  1.0  0.0
3             4  Female   23      16                      77  1.0  0.0
4             5  Female   31      17                      40  1.0  0.0
..          ...     ...  ...     ...                     ...  ...  ...
195         196  Female   35     120                      79  1.0  0.0
196         197  Female   45     126                      28  1.0  0.0
197         198    Male   32     126                      74  0.0  1.0
198         199    Male   32     137                      18  0.0  1.0
199         200    Male   30     137                      83  0.0  1.0

[200 rows x 7 columns]

In [52]:
df['Genre'] = df['Genre'].map({'Female': 0, 'Male': 1})
print(df,'\n')

print("Standard deviation:")
df.std()

     CustomerID  Genre  Age  Income  Spending Score (1-100)
0             1      1   19      15                      39
1             2      1   21      15                      81
2             3      0   20      16                       6
3             4      0   23      16                      77
4             5      0   31      17                      40
..          ...    ...  ...     ...                     ...
195         196      0   35     120                      79
196         197      0   45     126                      28
197         198      1   32     126                      74
198         199      1   32     137                      18
199         200      1   30     137                      83

[200 rows x 5 columns]

Standard deviation:

CustomerID                57.879185
Genre                      0.497633
Age                       13.969007
Income                    26.264721
Spending Score (1-100)    25.823522
dtype: float64

In [65]:
iris=pd.read_csv("IRIS.csv")

In [67]:
iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [101]:
iris['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [103]:
irisSet = (iris['species']== 'Iris-setosa')

#You're filtering the iris DataFrame to only keep the rows where irisSet is True

In [105]:
print(irisSet)

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: species, Length: 150, dtype: bool

In [107]:
print('\nIris-setosa\n')
print(iris[irisSet].describe())

Iris-setosa

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        5.00600     3.418000      1.464000      0.24400
std         0.35249     0.381024      0.173511      0.10721
min         4.30000     2.300000      1.000000      0.10000
25%         4.80000     3.125000      1.400000      0.20000
50%         5.00000     3.400000      1.500000      0.20000
75%         5.20000     3.675000      1.575000      0.30000
max         5.80000     4.400000      1.900000      0.60000

In [109]:
irisVer = (iris['species']== 'Iris-versicolor')

In [111]:
print('\nIris-versicolor\n')
print(iris[irisVer].describe())

Iris-versicolor

       sepal_length  sepal_width  petal_length  petal_width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000

In [113]:
irisVir = (iris['species']== 'Iris-virginica')

In [115]:
print('\nIris-virginica\n')
print(iris[irisVir].describe())

Iris-virginica

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000



Otherwise for percentile

percentile_25 = np.percentile(data, 25)  # 25th percentile
percentile_50 = np.percentile(data, 50)  # 50th percentile (median)
percentile_75 = np.percentile(data, 75)  # 75th percentile